name: Overwrite file

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish thesis update
        uses: actions/upload-artifact@v2
        with:
          name: file-to-overwrite
          path: main.pdf
      - name: Commit and push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.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 }}
          branch: master
          message: "${{ github.event.head_commit.message }}"
          committer_name: "${{ github.actor }}"
          committer_email: "${{ github.actor }}@users.noreply.github.com"
          repository: "flol3622/AR-Linked-BIM-viewer"
          src: file-to-overwrite
          dst: main.pdf
